version: "3.8"

services:
  django:
    image: "${DJANGO_IMAGE}"
    restart: always
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    volumes:
      - static:/static
    env_file:
      - env_vars/.env.prod

  nginx:
    container_name: nginx
    image: "${NGINX_IMAGE}"
    restart: always
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "8080:8080"
    depends_on:
      - django

  pgdb:
    env_file:
      - env_vars/.env.prod

  celery:
    image: "${CELERY_IMAGE}"
    restart: always
    env_file:
      - env_vars/.env.prod

  celery-beat:
    image: "${CELERY_BEAT_IMAGE}"
    restart: always
    env_file:
      - env_vars/.env.prod

volumes:
  static:
