version: "3.8"

services:
  django:
    build: .
    container_name: django
    working_dir: /usr/src/app/backend
    command: >
      sh -c "python manage.py makemigrations core &&
             python manage.py makemigrations users &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
      - logs:/usr/src/app/logs
      - static:/static
    ports:
      - "8000:8000"
    env_file:
      - env_vars/.env.prod
    depends_on:
      - redis
      - pgdb

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django

  pgdb:
    image: postgres:15.2-alpine
    container_name: pgdb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env_vars/.env.prod

  celery:
    build: .
    working_dir: /usr/src/app/backend
    command: celery -A backend worker -l INFO
    volumes:
      - .:/usr/src/app
    env_file:
      - env_vars/.env.prod
    depends_on:
      - django
      - redis
      - pgdb

  celery-beat:
    build: .
    working_dir: /usr/src/app/backend
    command: celery -A backend beat -s backend/celerybeat/celerybeat-schedule
    volumes:
      - .:/usr/src/app
    env_file:
      - env_vars/.env.prod
    depends_on:
      - celery

  redis:
    image: "redis:alpine"

volumes:
  logs: {}
  postgres_data:
  static:
