version: "3.11"

services:
  django:
    build: .
    container_name: django
    command: python backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
      - logs:/usr/src/app/logs
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  celery:
    build: .
    working_dir: /usr/src/app/backend
    command: celery -A backend worker -l INFO
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - django
      - redis

  celery-beat:
    build: .
    working_dir: /usr/src/app/backend
    command: celery -A backend beat -s backend/celerybeat/celerybeat-schedule
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - celery

  redis:
    image: "redis:alpine"

volumes:
  logs: {}
