name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: 3.11
        database-name:
          - github_actions
        database-password:
          - postgres
        database-user:
          - postgres
        database-host:
          - 127.0.0.1
        database-port:
          - 5432

    steps:
    - uses: actions/checkout@v2.4.0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2.3.1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Format with black
      working-directory: ./backend
      run: |
        # format the files with black
        pip install black
        black .
    - name: Lint with flake8
      working-directory: ./backend
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Sort imports
      working-directory: ./backend
      run: |
        pip install isort
        # stop the build if there are Python syntax errors or undefined names
        isort .
        isort --check --diff .
    - uses: actions/checkout@v2.4.0
    - name: Build image
      run: |
        docker-compose -f docker-compose-ci.yml build
    - name: Run migrations
      run: docker-compose -f docker-compose-ci.yml run django
    - name: Run tests
      run: docker-compose -f docker-compose-ci.yml run test
    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose-ci.yml" down
