name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  lint-and-format:
    name: Lint and Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      if: ${{ github.event_name == 'push' }}
    - uses: actions/checkout@v3
      if: ${{ github.event_name == 'pull_request' }}
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Set up Python 3.11
      uses: actions/setup-python@v2.3.1
      with:
        python-version: 3.11
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Lint with flake8
      working-directory: ./backend
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Format with black
      working-directory: ./backend
      run: |
        pip install black
        black .
    - name: Sort imports with isort
      working-directory: ./backend
      run: |
        pip install isort
        isort --profile black .
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions

  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build image
      run: |
        docker-compose -f docker-compose-ci.yml build
    - name: Run migrations
      run: docker-compose -f docker-compose-ci.yml run django
    - name: Run tests
      run: docker-compose -f docker-compose-ci.yml run test
    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose-ci.yml" down
